export const ErrorConstants = {
  // Form errors (validation)
  INVALID_EMAIL: 'Invalid email',
  REQUIRED_FIELD: 'This field is required',
  PASSWORD_WEAK:
    'Password must include letters, numbers, and special characters',
  EMAIL_ALREADY_EXISTS: 'A user with this email is already registered',
  INVALID_CODE: 'Invalid confirmation code',
  FIELD_TOO_SHORT: 'Field is too short',
  FIELD_TOO_LONG: 'Field is too long',
  INVALID_PASSWORD: 'Invalid password',

  // Service errors
  NO_REFRESH_COOKIE: 'Refresh token is missing in cookies',
  REFRESH_TOKEN_EXPIRED: 'Refresh token has expired',
  REFRESH_TOKEN_INVALID: 'Refresh token is invalid',
  REFRESH_TOKEN_SESSION_MISMATCH: 'Refresh token does not match the session',
  CONFIRMATION_CODE_INVALID:
    'Confirmation code is incorrect, expired, or already used',
  USER_ALREADY_CONFIRMED_CODE: 'User is already confirmed',
  USER_AGENT_EMPTY: 'userAgent header is empty',
  USER_AGENT_NOT_CORRECT: 'userAgent header is not correct',
  CONFIRMATION_LINK_EXPIRED: 'Confirmation link in email has expired',
  SESSION_NOT_FOUND: 'Session does not exist',
  SESSION_CREATE_ERROR: 'Session is not created',
  SESSION_DELETE_ERROR: 'Session is not deleted',
  USER_WITH_EMAIL_NOT_EXIST: 'User with this email does not exist',
  USER_ALREADY_CONFIRMED: 'User is already confirmed',
  RECOVERY_CODE_INCORRECT: 'Recovery code is incorrect',
  RECOVERY_CODE_EXPIRED: 'Recovery code has expired',
  USER_NOT_CONFIRMED: 'User is not confirmed',
  USER_NOT_FOUND: 'User not found',
  UNAUTHORIZED: 'No access (authorization failed)',
  FORBIDDEN: 'Access denied',
  INTERNAL_SERVER_ERROR: 'Internal server error',
  EMAIL_SEND_FAILED: 'Failed to send email',
  INVALID_CREDENTIALS: 'Invalid login credentials',
  ACTION_NOT_ALLOWED: 'Action not allowed',
  REGISTRATION_FAILED: 'User registration failed',
  RECAPTCHA_TOKEN_REQUIRED: 'reCAPTCHA token is required',
  RECAPTCHA_VERIFICATION_FAILED: 'reCAPTCHA verification failed',
  LOGIN_ALREADY_TAKEN: 'Login is already taken',
  EMAIL_ALREADY_TAKEN: 'Email is already in use',
  POST_NOT_FOUND: 'Post not found',
  FILE_ID_NOT_FOUND: 'Field Id not found',
};
