def app
pipeline {
    agent any
    environment {
        ENV_TYPE = "production"
        PORT = 4136
        NAMESPACE = "socialnetwork-ai-com"
        REGISTRY_HOSTNAME = "socialnetworkai"
        PROJECT = "soc-net-main"
        SERVICE="main"
        REGISTRY = "registry.hub.docker.com"
        DEPLOYMENT_NAME = "soc-net-main-deployment"
        IMAGE_NAME = "${env.BUILD_ID}_${env.ENV_TYPE}_${env.GIT_COMMIT}"
        DOCKER_BUILD_NAME = "${env.REGISTRY_HOSTNAME}/${env.PROJECT}:${env.IMAGE_NAME}"
    }

    stages {
        stage('Clone repository') {
            steps {
                checkout scm
            }
        }

        stage('Install dependencies') {
            steps {
                script {
                     sh '''
                        export NVM_DIR="$HOME/.nvm"
                        [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
                        nvm use v20.5.1 --ignore-prev-failure
                        npm ci
                     '''
                }
            }
        }
//         stage('Unit tests') {
//             steps {
//                 script {
//                     sh '''
//                        export NVM_DIR="$HOME/.nvm"
//                        [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
//                        nvm use --lts
//                        yarn install
//                        yarn test
//                     '''
//                 }
//             }
//         }
//         stage('e2e tests') {
//             steps {
//                 script {
//                     sh '''
//                         # Устанавливаем путь к конкретной версии Node.js
//                         NODE_BIN_PATH="/home/abazunts/.nvm/versions/node/v20.5.1/bin"
//
//                         # Проверяем что она существует
//                         if [ -x "$NODE_BIN_PATH/node" ]; then
//                             # Используем её
//                             export PATH="$NODE_BIN_PATH:$PATH"
//                             echo "✅ Using Node.js from: $NODE_BIN_PATH"
//                             echo "✅ Version: $(node --version)"
//
//                             npm run test:e2e
//                         else
//                             echo "❌ Node.js not found at $NODE_BIN_PATH"
//                             exit 1
//                         fi
//                     '''
//                 }
//             }
//         }
        stage('Build docker image') {
            steps {
                echo "Build image started..."
                    script {
                       app = docker.build("${env.DOCKER_BUILD_NAME}", "--build-arg service=${env.SERVICE} --build-arg port=${env.PORT} -f ./apps/${env.SERVICE}/Dockerfile ./")
                    }
                echo "Build image finished..."
            }
        }
        stage('Push docker image') {
             steps {
                 echo "Push image started..."
                     script {
                        docker.withRegistry("https://${env.REGISTRY}", 'socialnetwork-ai-com') {
                            app.push("${env.IMAGE_NAME}")
                        }
                     }
                 echo "Push image finished..."
             }
       }
       stage('Delete image local') {
             steps {
                 script {
                    sh "docker rmi -f ${env.DOCKER_BUILD_NAME}"
                 }
             }
        }
        stage('Preparing deployment') {
             steps {
                 echo "Preparing started..."
                     sh 'ls -ltr'
                     sh 'pwd'
                     sh "chmod +x ./apps/${env.SERVICE}/preparingDeploy.sh"
                     sh "./apps/${env.SERVICE}/preparingDeploy.sh ${env.REGISTRY_HOSTNAME} ${env.PROJECT} ${env.IMAGE_NAME} ${env.DEPLOYMENT_NAME} ${env.PORT} ${env.NAMESPACE}"
                     sh "cat ./apps/${env.SERVICE}/deployment.yaml"
             }
        }
        stage('Deploy to Kubernetes') {
             steps {
                 withKubeConfig([credentialsId: 'prod-kubernetes']) {
                    sh "kubectl apply -f ./apps/${env.SERVICE}/deployment.yaml"
                    sh "kubectl rollout status deployment/${env.DEPLOYMENT_NAME} --namespace=${env.NAMESPACE}"
                    sh "kubectl get services -o wide"
                 }
             }
        }
    }
}
